// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shared/proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNKNOWN    TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PROCESSING TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_SUCCESS    TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED     TransactionStatus = 3
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNKNOWN",
		1: "TRANSACTION_STATUS_PROCESSING",
		2: "TRANSACTION_STATUS_SUCCESS",
		3: "TRANSACTION_STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNKNOWN":    0,
		"TRANSACTION_STATUS_PROCESSING": 1,
		"TRANSACTION_STATUS_SUCCESS":    2,
		"TRANSACTION_STATUS_FAILED":     3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_transaction_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_DEPOSIT     TransactionType = 1
	TransactionType_TRANSACTION_TYPE_WITHDRAW    TransactionType = 2
	TransactionType_TRANSACTION_TYPE_PAYMENT     TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_DEPOSIT",
		2: "TRANSACTION_TYPE_WITHDRAW",
		3: "TRANSACTION_TYPE_PAYMENT",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_DEPOSIT":     1,
		"TRANSACTION_TYPE_WITHDRAW":    2,
		"TRANSACTION_TYPE_PAYMENT":     3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_transaction_proto_enumTypes[1].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_shared_proto_transaction_proto_enumTypes[1]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{1}
}

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=proto.TransactionType" json:"type,omitempty"`
	ToAccountId   *wrapperspb.Int32Value `protobuf:"bytes,4,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_shared_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *TransactionRequest) GetToAccountId() *wrapperspb.Int32Value {
	if x != nil {
		return x.ToAccountId
	}
	return nil
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TransactionStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.TransactionStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_shared_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNKNOWN
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_shared_proto_transaction_proto protoreflect.FileDescriptor

const file_shared_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1eshared/proto/transaction.proto\x12\x05proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb8\x01\n" +
	"\x12TransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.proto.TransactionTypeR\x04type\x12?\n" +
	"\rto_account_id\x18\x04 \x01(\v2\x1b.google.protobuf.Int32ValueR\vtoAccountId\"a\n" +
	"\x13TransactionResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.proto.TransactionStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x95\x01\n" +
	"\x11TransactionStatus\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_UNKNOWN\x10\x00\x12!\n" +
	"\x1dTRANSACTION_STATUS_PROCESSING\x10\x01\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x03*\x8e\x01\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_DEPOSIT\x10\x01\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_WITHDRAW\x10\x02\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_PAYMENT\x10\x032^\n" +
	"\x12TransactionService\x12H\n" +
	"\x0fSendTransaction\x12\x19.proto.TransactionRequest\x1a\x1a.proto.TransactionResponseB\x15Z\x13/shared/proto;protob\x06proto3"

var (
	file_shared_proto_transaction_proto_rawDescOnce sync.Once
	file_shared_proto_transaction_proto_rawDescData []byte
)

func file_shared_proto_transaction_proto_rawDescGZIP() []byte {
	file_shared_proto_transaction_proto_rawDescOnce.Do(func() {
		file_shared_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_transaction_proto_rawDesc), len(file_shared_proto_transaction_proto_rawDesc)))
	})
	return file_shared_proto_transaction_proto_rawDescData
}

var file_shared_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shared_proto_transaction_proto_goTypes = []any{
	(TransactionStatus)(0),        // 0: proto.TransactionStatus
	(TransactionType)(0),          // 1: proto.TransactionType
	(*TransactionRequest)(nil),    // 2: proto.TransactionRequest
	(*TransactionResponse)(nil),   // 3: proto.TransactionResponse
	(*wrapperspb.Int32Value)(nil), // 4: google.protobuf.Int32Value
}
var file_shared_proto_transaction_proto_depIdxs = []int32{
	1, // 0: proto.TransactionRequest.type:type_name -> proto.TransactionType
	4, // 1: proto.TransactionRequest.to_account_id:type_name -> google.protobuf.Int32Value
	0, // 2: proto.TransactionResponse.status:type_name -> proto.TransactionStatus
	2, // 3: proto.TransactionService.SendTransaction:input_type -> proto.TransactionRequest
	3, // 4: proto.TransactionService.SendTransaction:output_type -> proto.TransactionResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shared_proto_transaction_proto_init() }
func file_shared_proto_transaction_proto_init() {
	if File_shared_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_transaction_proto_rawDesc), len(file_shared_proto_transaction_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_transaction_proto_goTypes,
		DependencyIndexes: file_shared_proto_transaction_proto_depIdxs,
		EnumInfos:         file_shared_proto_transaction_proto_enumTypes,
		MessageInfos:      file_shared_proto_transaction_proto_msgTypes,
	}.Build()
	File_shared_proto_transaction_proto = out.File
	file_shared_proto_transaction_proto_goTypes = nil
	file_shared_proto_transaction_proto_depIdxs = nil
}
