// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: shared/proto/transaction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNKNOWN TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_SUCCESS TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED  TransactionStatus = 3
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNKNOWN",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_SUCCESS",
		3: "TRANSACTION_STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNKNOWN": 0,
		"TRANSACTION_STATUS_PENDING": 1,
		"TRANSACTION_STATUS_SUCCESS": 2,
		"TRANSACTION_STATUS_FAILED":  3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_transaction_proto_enumTypes[0].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_shared_proto_transaction_proto_enumTypes[0]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{0}
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAccountId   int32                  `protobuf:"varint,1,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_shared_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *DepositRequest) GetToAccountId() int32 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *DepositRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int32                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawRequest) Reset() {
	*x = WithdrawRequest{}
	mi := &file_shared_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRequest) ProtoMessage() {}

func (x *WithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRequest.ProtoReflect.Descriptor instead.
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawRequest) GetFromAccountId() int32 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *WithdrawRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAccountId int32                  `protobuf:"varint,1,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId   int32                  `protobuf:"varint,2,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequest) Reset() {
	*x = PaymentRequest{}
	mi := &file_shared_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequest) ProtoMessage() {}

func (x *PaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequest.ProtoReflect.Descriptor instead.
func (*PaymentRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentRequest) GetFromAccountId() int32 {
	if x != nil {
		return x.FromAccountId
	}
	return 0
}

func (x *PaymentRequest) GetToAccountId() int32 {
	if x != nil {
		return x.ToAccountId
	}
	return 0
}

func (x *PaymentRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TransactionStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.TransactionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_shared_proto_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *DepositResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNKNOWN
}

type WithdrawResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TransactionStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.TransactionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawResponse) Reset() {
	*x = WithdrawResponse{}
	mi := &file_shared_proto_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawResponse) ProtoMessage() {}

func (x *WithdrawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawResponse.ProtoReflect.Descriptor instead.
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNKNOWN
}

type PaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TransactionStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=proto.TransactionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_shared_proto_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNKNOWN
}

var File_shared_proto_transaction_proto protoreflect.FileDescriptor

const file_shared_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1eshared/proto/transaction.proto\x12\x05proto\"L\n" +
	"\x0eDepositRequest\x12\"\n" +
	"\rto_account_id\x18\x01 \x01(\x05R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"Q\n" +
	"\x0fWithdrawRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x05R\rfromAccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"t\n" +
	"\x0ePaymentRequest\x12&\n" +
	"\x0ffrom_account_id\x18\x01 \x01(\x05R\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x02 \x01(\x05R\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"C\n" +
	"\x0fDepositResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.proto.TransactionStatusR\x06status\"D\n" +
	"\x10WithdrawResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.proto.TransactionStatusR\x06status\"C\n" +
	"\x0fPaymentResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.proto.TransactionStatusR\x06status*\x92\x01\n" +
	"\x11TransactionStatus\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_UNKNOWN\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_SUCCESS\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x032\xc5\x01\n" +
	"\x12TransactionService\x128\n" +
	"\aDeposit\x12\x15.proto.DepositRequest\x1a\x16.proto.DepositResponse\x12;\n" +
	"\bWithdraw\x12\x16.proto.WithdrawRequest\x1a\x17.proto.WithdrawResponse\x128\n" +
	"\aPayment\x12\x15.proto.PaymentRequest\x1a\x16.proto.PaymentResponseB\x15Z\x13/shared/proto;protob\x06proto3"

var (
	file_shared_proto_transaction_proto_rawDescOnce sync.Once
	file_shared_proto_transaction_proto_rawDescData []byte
)

func file_shared_proto_transaction_proto_rawDescGZIP() []byte {
	file_shared_proto_transaction_proto_rawDescOnce.Do(func() {
		file_shared_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_transaction_proto_rawDesc), len(file_shared_proto_transaction_proto_rawDesc)))
	})
	return file_shared_proto_transaction_proto_rawDescData
}

var file_shared_proto_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shared_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shared_proto_transaction_proto_goTypes = []any{
	(TransactionStatus)(0),   // 0: proto.TransactionStatus
	(*DepositRequest)(nil),   // 1: proto.DepositRequest
	(*WithdrawRequest)(nil),  // 2: proto.WithdrawRequest
	(*PaymentRequest)(nil),   // 3: proto.PaymentRequest
	(*DepositResponse)(nil),  // 4: proto.DepositResponse
	(*WithdrawResponse)(nil), // 5: proto.WithdrawResponse
	(*PaymentResponse)(nil),  // 6: proto.PaymentResponse
}
var file_shared_proto_transaction_proto_depIdxs = []int32{
	0, // 0: proto.DepositResponse.status:type_name -> proto.TransactionStatus
	0, // 1: proto.WithdrawResponse.status:type_name -> proto.TransactionStatus
	0, // 2: proto.PaymentResponse.status:type_name -> proto.TransactionStatus
	1, // 3: proto.TransactionService.Deposit:input_type -> proto.DepositRequest
	2, // 4: proto.TransactionService.Withdraw:input_type -> proto.WithdrawRequest
	3, // 5: proto.TransactionService.Payment:input_type -> proto.PaymentRequest
	4, // 6: proto.TransactionService.Deposit:output_type -> proto.DepositResponse
	5, // 7: proto.TransactionService.Withdraw:output_type -> proto.WithdrawResponse
	6, // 8: proto.TransactionService.Payment:output_type -> proto.PaymentResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shared_proto_transaction_proto_init() }
func file_shared_proto_transaction_proto_init() {
	if File_shared_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_transaction_proto_rawDesc), len(file_shared_proto_transaction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_transaction_proto_goTypes,
		DependencyIndexes: file_shared_proto_transaction_proto_depIdxs,
		EnumInfos:         file_shared_proto_transaction_proto_enumTypes,
		MessageInfos:      file_shared_proto_transaction_proto_msgTypes,
	}.Build()
	File_shared_proto_transaction_proto = out.File
	file_shared_proto_transaction_proto_goTypes = nil
	file_shared_proto_transaction_proto_depIdxs = nil
}
