// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Account struct {
	ID          int32     `json:"id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	Amount      int32     `json:"amount"`
	CreatedDate time.Time `json:"created_date"`
}

type Transaction struct {
	ID            int32     `json:"id"`
	Type          int32     `json:"type"`
	Status        int32     `json:"status"`
	Amount        int32     `json:"amount"`
	Message       string    `json:"message"`
	FromAccountID int32     `json:"from_account_id"`
	ToAccountID   int32     `json:"to_account_id"`
	CreatedDate   time.Time `json:"created_date"`
}
